import mongoose from "mongoose";

/**
 * Mongoose Schema representing the complete lifecycle of a Job Application in ApplyPilot.
 */
const jobSchema = new mongoose.Schema(
  {
    // Unique human-readable or UUID identifier for the application job
    jobId: {
      type: String,
      required: [true, "jobId is required"],
      unique: true,
      index: true,
    },

    // Current workflow status
    status: {
      type: String,
      enum: [
        "QUEUED",
        "PROCESSING",
        "PARSING_JOB",
        "TAILORING_RESUME",
        "GENERATING_COVER_LETTER",
        "COMPOSING_EMAIL",
        "SENDING_EMAIL",
        "SAVING_TO_SENT",
        "COMPLETED",
        "FAILED",
      ],
      default: "QUEUED",
      index: true,
    },

    // Original job description provided by client
    originalJobDescription: {
      type: String,
      required: [true, "originalJobDescription is required"],
    },

    // Structured job details extracted via OpenAI
    parsedJob: {
      title: { type: String, default: null, index: true },
      company: { type: String, default: null, index: true },
      location: { type: String, default: null },
      employmentType: { type: String, default: null },

      experienceMin: { type: Number, default: null },
      experienceMax: { type: Number, default: null },

      salaryMin: { type: Number, default: null },
      salaryMax: { type: Number, default: null },
      salaryCurrency: { type: String, default: null },

      skills: { type: String, default: null },
      responsibilities: { type: String, default: null },
      requirements: { type: String, default: null },
      niceToHave: { type: String, default: null },

      applicationEmail: { type: String, default: null },
      applicationUrl: { type: String, default: null },

      sourceUrl: { type: String, default: null },
      sourcePlatform: { type: String, default: null },

      description: { type: String, default: null },
    },

    // Resume tailored by Resume API
    resume: {
      requestStatus: {
        type: String,
        enum: ["PENDING", "PROCESSING", "COMPLETED", "FAILED"],
        default: "PENDING",
      },
      urls: {
        type: [String],
        default: [],
      },
    },

    // Cover letter generated by OpenAI
    coverLetter: {
      status: {
        type: String,
        enum: ["PENDING", "PROCESSING", "COMPLETED", "FAILED"],
        default: "PENDING",
      },
      content: {
        type: String,
        default: null,
      },
    },

    // Email delivery and IMAP synchronization state
    email: {
      recruiterEmail: { type: String, default: null },
      subject: { type: String, default: null },
      body: { type: String, default: null },
      messageId: { type: String, default: null },

      // Track SMTP and IMAP independently for safe retries
      smtpStatus: {
        type: String,
        enum: ["PENDING", "SENT", "FAILED"],
        default: "PENDING",
      },
      sentFolderStatus: {
        type: String,
        enum: ["PENDING", "SAVED", "FAILED", "SKIPPED"],
        default: "PENDING",
      },
      sentAt: {
        type: Date,
        default: null,
      },
    },

    // Detailed processing progress and stage metrics
    processing: {
      currentStage: {
        type: String,
        default: "QUEUED",
      },
      progress: {
        type: Number,
        default: 0,
        min: 0,
        max: 100,
      },
      startedAt: {
        type: Date,
        default: null,
      },
      completedAt: {
        type: Date,
        default: null,
      },
    },

    // Granular activity timeline events
    timeline: [
      {
        stage: { type: String, required: true },
        status: { type: String, required: true }, // e.g. "QUEUED", "STARTED", "COMPLETED", "FAILED"
        message: { type: String, required: true },
        createdAt: { type: Date, default: Date.now },
      },
    ],

    // Detailed error information if a stage fails
    error: {
      stage: { type: String, default: null },
      message: { type: String, default: null },
    },
  },
  {
    timestamps: true, // Automatically manages createdAt and updatedAt
  }
);

// Compound / single indexes for queries & sorting
jobSchema.index({ createdAt: -1 });
jobSchema.index({ status: 1, createdAt: -1 });
jobSchema.index({ "parsedJob.title": "text", "parsedJob.company": "text" });

const Job = mongoose.model("Job", jobSchema);

export default Job;
